### PR TITLE
Simplifications and python styling

### PR DESCRIPTION
**Pull request by ocaballeror**
A few other commits here to simplify some overly-complicated parts of the code and, most importantly, to follow python PEP8 style guide.

Of course, feel free to dismiss any of these changes as "too nitpicky" and I'll gladly revert them.

### CODE REVIEW

**Review by cperales — APPROVED** [review]
Argh, typos... Besides, I should implement loggers and not prints. Thanks man!

**Comment by ocaballeror** [comment]
You're welcome!

**Review by cperales — COMMENTED** [review]
Some changes are faster and cool, other as changing list by numpy arrays I'm not too convinced about them.

I pull your pull request branch locally, and I'm selecting code by hand. I'll be able to modify the code and submit as another pull request in this weekend, probably.

**Review by cperales — APPROVED** [review]

**Comment by cperales** [comment]
Pull request https://github.com/cperales/foucluster/pull/4 with your main modifications are accepted. Some changes, related with lists and conditionals are not accepted. Explanation in commit 4ebc0c7

**Pull request closed without merging**
